
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=dataset_analysis
      - DB_USER=postgres
      - DB_PASSWORD=

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: